definitions:
  model.Student:
    properties:
      age:
        type: integer
      major:
        type: string
      name:
        type: string
      studentId:
        type: string
    type: object
  response.Response:
    properties:
      code:
        type: integer
      data: {}
      message:
        type: string
      requestId:
        type: string
      requestKey:
        type: string
      status:
        type: string
    type: object
info:
  contact: {}
paths:
  /student:
    post:
      consumes:
      - application/json
      description: Create a new student entry in the database
      parameters:
      - description: requestId
        in: header
        name: requestId
        type: string
      - description: Student data
        in: body
        name: student
        required: true
        schema:
          $ref: '#/definitions/model.Student'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/response.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.Response'
      summary: Create a new student
  /student/{studentId}:
    delete:
      description: Remove a student entry from the database by Student ID
      parameters:
      - description: requestId
        in: header
        name: requestId
        type: string
      - description: Student ID
        in: path
        name: studentId
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Response'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/response.Response'
      summary: Delete a student by Student ID
    get:
      consumes:
      - application/json
      description: Retrieve a student from the database by Student ID
      parameters:
      - description: requestId
        in: header
        name: requestId
        type: string
      - description: Student ID
        in: path
        name: studentId
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Response'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/response.Response'
      summary: Get a student by Student ID
    put:
      consumes:
      - application/json
      description: Update a student entry in the database
      parameters:
      - description: requestId
        in: header
        name: requestId
        type: string
      - description: Student ID
        in: path
        name: studentId
        required: true
        type: string
      - description: Student data
        in: body
        name: student
        required: true
        schema:
          $ref: '#/definitions/model.Student'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.Response'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/response.Response'
      summary: Update a student by Student ID
swagger: "2.0"
